schema = 1
extends = "soc/sm7635"

[device]
name = "asteroids"
vendor = "nothing"

[kernel]
defconfigs = [
  "gki_defconfig",
  "vendor/pineapple_perf.config",
  "vendor/asteroids_perf.config",
]

[external_modules]
paths = [
  "noth/fingerprint",
  "noth/touchscreen",
]

[meta]
tested_tree = "https://github.com/AKoskovich/android_kernel_nothing_sm7635@8ee84a2765a8820a1c4fd5c53f3d6d1f216a9941"
